name: ou_est_mon_fric
description: L'app qui rend l'argent entre potes moins gÃªnant
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.4.0
  
  # HTTP & API
  dio: ^5.4.0
  
  # Auth & Security
  flutter_secure_storage: ^9.0.0
  google_sign_in: ^6.2.1
  google_sign_in_web: ^0.12.3+3
  
  # Local Storage
  shared_preferences: ^2.5.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # UI & Animations PREMIUM
  flutter_animate: ^4.5.0
  animated_text_kit: ^4.2.2
  lottie: ^3.0.0
  rive: ^0.13.0
  flutter_staggered_animations: ^1.1.1
  
  # Icons & Graphics
  iconsax: ^0.0.8
  flutter_svg: ^2.0.9
  
  # Effects
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1

  contacts_service: ^0.6.3
  
  # Utils
  intl: ^0.20.2
  image_picker: ^1.0.7
  url_launcher: ^6.2.2
  permission_handler: ^11.1.0
  
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/google_logo.svg